services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: pancore-backend-${ENV:-main}
    env_file:
      - .env
    restart: always
    networks:
      - inner-network

  nginx:
    image: ${FRONTEND_IMAGE}
    container_name: pancore-nginx-${ENV:-main}
    env_file:
      - .env
    ports:
      - '${NGINX_PORT:-80}:80'
      - '443:443'
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - API_KEY=${API_KEY}
      - NGINX_ENVSUBST_FILTER=BACKEND_PORT|API_KEY
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - inner-network
    depends_on:
      - backend

networks:
  inner-network:
    driver: bridge
